### ISSUE TITLE
Clean up application notebooks

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/cell_classification#64]
**Is your feature request related to a problem? Please describe.**
The current application notebooks have a bunch of functions defined within them, rather than imported. In addition, there are some manual steps (defining marker names) that should probably be handled automatically. There's also stuff about the google drive integration, example datasets, etc that was copied from `ark` that we should remove or update to be correct. 

All of this cleanup will be good to do before we start having people try out the pipeline so we can figure out what's working and what isn't.

**Comment by JLrumberger** [comment]
### Instructions
I started and did a first refactor, but I think a design doc is needed. Goal is to re-organize the code in `predict.ipynb`, such that it is easy to use while having enough degrees of freedom to be not embarrassing. 

**Relevant background**
This feature should ensure great UX for users when loading and using our model for inference on their own data.

**Design overview**
The utility needed for inference on new data includes the following:
- calculate or load `normalization_dict`
- initialize model and download weights (from web) if they are not already loaded
- detect & use GPU if available
- make predictions based on single FoV paths or a folder of FoVs
- allow for half-res inference
- allow for test time augmentations
- automatically save predictions and cell_table.csv 
- inspect input and predictions

**Code mockup**
```
class Nimbus(deepcell.applications.Application)

def init
list fov_paths
list exclude_channels
func segmentation_naming_convention
str output_dir
bool half_resolution
bool save_predictions

def check_inputs
# check inputs and return well written error messages

def prepare_normalization_dict
# loads or calculates and saves normalization dict

def download_weights
# downloads weights from online repo

def get_model
# instantiates model and loads weights

def prep_input
# prepares input data for prediction including resizing

def prep_output
# prepares output including resizing

def predict(fov_paths)
# predicts all non excluded marker images from fovs in fov_paths and saves predictions


class ViewerWidget

def init
list fov_paths
func segmentation_naming_convention
str output_dir

def load_input

def load_output

def start_viewer
# dropdown FoVs
# dropdown with channels
# shows input and output side-by-side for fov/channel combination
```

**Required inputs**

- Model weights stored accessible in the cloud, probably add md5 check after download
- fov_paths: list of strings, each entry is a path to a folder containing one image per marker channel
- exclude_channels: list of strings containing names of marker images to exclude
- segmentation_naming_convention: function that takes in a fov_path string and returns the according path to the segmentation image
- output_dir: string, path where the output will be stored
- half_resolution: bool. If we want to do inference on resized images
- save_predictions: bool. Whether to save predictions as image or not.

**Output files**
- folder of predictions as image
- cell_table.csv that contains the mean-per-cell predicted marker expression

**Timeline**
Give a rough estimate for how long you think the project will take. In general, it's better to be too conservative rather than too optimistic. 
- [x] A couple days
- [ ] A week
- [ ] Multiple weeks. For large projects, make sure to agree on a plan that isn't just a single monster PR at the end. 

Estimated date when a fully implemented version will be ready for review: 08/15

Estimated date when the finalized project will be merged in: 08/18
