### ISSUE TITLE
Unexplainable "tiling shadows" in prediction masks

### ISSUE THREAD

**Issue by svntrx** [angelolab/cell_classification#68]
Dear Lorenz, der devteam,

First of all thanks a lot for this cool and exciting new tool! Looking forward to reading the preprint soon.
I tried to run Nimbus on some of my melanoma samples and ran into some peculiarities. To me it seems that while the predictions for positivity are spot-on for some markers, I see weird square-shaped shadows on some other channels with the dimensions of 1/3rd the fov-size (see image, these FOVs are 800x800µm). Further, for some channels (e.g. CD86 in this example), it appears to me that antibody-mediated background signal is overemphazised a bit when comparing the input image (with "true" positive cells in the fov centre) and the corresponding prediction. Do you have ideas of where the issue may lie here? Would be happy to get your insights on this. I ran nimbus on the most recent version and with default args for all functions except input_shape for Nimbus(), which i put to [512,512] as I am running the package on my laptop.

Thanks a lot for your help!

Best wishes,
Sven

![nimbus](https://github.com/angelolab/Nimbus/assets/93774912/a85f7978-19d3-4e72-bb8d-615b2575c334)

**Comment by JLrumberger** [comment]
Hi @svntrx,

first of all thanks for trying Nimbus early on and I am really happy that it runs fine on your notebook. The square-shaped shadows seem to be an artifact from tile-and-stitch inference and we have seen them in the past on our samples too, but thought they were gone with the newest version. Good that you bring it up, I think I'll need to change the inference routine to avoid these artifact patterns. 
Regarding the antibody mediated background, my guess is that right now, the model does not generalize well for CD86 and melanoma tissues. I think this is because neither CD86 nor melanoma tissues are part of the training data yet. I'd love to get my hands on your data, is it already published somewhere?

Best,
Lorenz
